# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'motion-cocoapods'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'LineLayout'
  app.deployment_target = '5.1'

  app.pods do
    pod 'PSTCollectionView'
  end
  app.libs << '-fobjc-arc'
end
